"""add appliance stock class

Revision ID: 13278e3c9f46
Revises: c31f4a2e9d70
Create Date: 2026-08-27 15:11:24.815425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13278e3c9f46'
down_revision = 'c31f4a2e9d70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appliance_unit', sa.Column('stock_class', sa.String(length=30), server_default='new', nullable=False))
    op.create_index(op.f('ix_appliance_unit_stock_class'), 'appliance_unit', ['stock_class'], unique=False)
    op.create_index('ix_appliance_unit_stock_class_status', 'appliance_unit', ['stock_class', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_appliance_unit_stock_class_status', table_name='appliance_unit')
    op.drop_index(op.f('ix_appliance_unit_stock_class'), table_name='appliance_unit')
    op.drop_column('appliance_unit', 'stock_class')
    # ### end Alembic commands ###
