"""add appliance color

Revision ID: 43b93daf2f26
Revises: 13278e3c9f46
Create Date: 2026-08-28 10:54:36.372396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43b93daf2f26'
down_revision = '13278e3c9f46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appliance_receiving_line', sa.Column('color', sa.String(length=80), nullable=True))
    op.add_column('appliance_unit', sa.Column('color', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appliance_unit', 'color')
    op.drop_column('appliance_receiving_line', 'color')
    # ### end Alembic commands ###
