"""add appliance model specs catalog

Revision ID: 4893e0c10a2a
Revises: 43b93daf2f26
Create Date: 2026-08-28 15:06:19.026867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4893e0c10a2a'
down_revision = '43b93daf2f26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appliance_model_spec',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand', sa.String(length=120), nullable=False),
    sa.Column('model_number', sa.String(length=120), nullable=False),
    sa.Column('normalized_brand', sa.String(length=120), nullable=False),
    sa.Column('normalized_model', sa.String(length=120), nullable=False),
    sa.Column('size_value', sa.Float(), nullable=True),
    sa.Column('size_unit', sa.String(length=20), nullable=True),
    sa.Column('color', sa.String(length=80), nullable=True),
    sa.Column('notes_block', sa.Text(), nullable=True),
    sa.Column('exact_model_confirmed', sa.Boolean(), nullable=False),
    sa.Column('confirmed_model', sa.String(length=120), nullable=True),
    sa.Column('suggested_model', sa.String(length=120), nullable=True),
    sa.Column('appliance_type', sa.String(length=160), nullable=True),
    sa.Column('match_notes', sa.String(length=500), nullable=True),
    sa.Column('confidence', sa.String(length=20), nullable=False),
    sa.Column('source_name', sa.String(length=250), nullable=True),
    sa.Column('source_url', sa.String(length=2000), nullable=True),
    sa.Column('sources_json', sa.Text(), nullable=True),
    sa.Column('confirmed_by_id', sa.Integer(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['confirmed_by_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('normalized_brand', 'normalized_model', name='uq_appliance_model_spec_brand_model')
    )
    op.create_index('ix_appliance_model_spec_brand_model', 'appliance_model_spec', ['normalized_brand', 'normalized_model'], unique=False)
    op.create_index(op.f('ix_appliance_model_spec_confirmed_at'), 'appliance_model_spec', ['confirmed_at'], unique=False)
    op.create_index(op.f('ix_appliance_model_spec_confirmed_by_id'), 'appliance_model_spec', ['confirmed_by_id'], unique=False)
    op.create_index(op.f('ix_appliance_model_spec_created_at'), 'appliance_model_spec', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_appliance_model_spec_created_at'), table_name='appliance_model_spec')
    op.drop_index(op.f('ix_appliance_model_spec_confirmed_by_id'), table_name='appliance_model_spec')
    op.drop_index(op.f('ix_appliance_model_spec_confirmed_at'), table_name='appliance_model_spec')
    op.drop_index('ix_appliance_model_spec_brand_model', table_name='appliance_model_spec')
    op.drop_table('appliance_model_spec')
    # ### end Alembic commands ###
