"""add appliance issue and movement

Revision ID: 87dc3aa9b0c4
Revises: ab9ee67cc6c1
Create Date: 2026-08-26 13:41:29.999685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87dc3aa9b0c4'
down_revision = 'ab9ee67cc6c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appliance_issue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('issue_number', sa.String(length=40), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('technician_id', sa.Integer(), nullable=True),
    sa.Column('work_order_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('issued_at', sa.DateTime(), nullable=False),
    sa.Column('issued_by_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['issued_by_id'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['technician_id'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouse.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_orders.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('issue_number', name='uq_appliance_issue_number')
    )
    op.create_index(op.f('ix_appliance_issue_issue_number'), 'appliance_issue', ['issue_number'], unique=True)
    op.create_index(op.f('ix_appliance_issue_issued_at'), 'appliance_issue', ['issued_at'], unique=False)
    op.create_index(op.f('ix_appliance_issue_issued_by_id'), 'appliance_issue', ['issued_by_id'], unique=False)
    op.create_index(op.f('ix_appliance_issue_status'), 'appliance_issue', ['status'], unique=False)
    op.create_index('ix_appliance_issue_technician_date', 'appliance_issue', ['technician_id', 'issued_at'], unique=False)
    op.create_index(op.f('ix_appliance_issue_technician_id'), 'appliance_issue', ['technician_id'], unique=False)
    op.create_index(op.f('ix_appliance_issue_warehouse_id'), 'appliance_issue', ['warehouse_id'], unique=False)
    op.create_index('ix_appliance_issue_warehouse_status', 'appliance_issue', ['warehouse_id', 'status'], unique=False)
    op.create_index('ix_appliance_issue_work_order', 'appliance_issue', ['work_order_id'], unique=False)
    op.create_index(op.f('ix_appliance_issue_work_order_id'), 'appliance_issue', ['work_order_id'], unique=False)
    op.create_table('appliance_issue_line',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('issue_id', sa.Integer(), nullable=False),
    sa.Column('line_no', sa.Integer(), nullable=False),
    sa.Column('appliance_unit_id', sa.Integer(), nullable=False),
    sa.Column('current_work_order_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('installed_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('inventory_number_snapshot', sa.String(length=40), nullable=False),
    sa.Column('appliance_type_snapshot', sa.String(length=120), nullable=True),
    sa.Column('brand_snapshot', sa.String(length=100), nullable=True),
    sa.Column('model_number_snapshot', sa.String(length=120), nullable=True),
    sa.Column('serial_number_snapshot', sa.String(length=160), nullable=True),
    sa.Column('size_value_snapshot', sa.Float(), nullable=True),
    sa.Column('size_unit_snapshot', sa.String(length=20), nullable=True),
    sa.Column('condition_snapshot', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['appliance_unit_id'], ['appliance_unit.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['current_work_order_id'], ['work_orders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['issue_id'], ['appliance_issue.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('issue_id', 'appliance_unit_id', name='uq_appliance_issue_line_unit'),
    sa.UniqueConstraint('issue_id', 'line_no', name='uq_appliance_issue_line_number')
    )
    op.create_index(op.f('ix_appliance_issue_line_appliance_unit_id'), 'appliance_issue_line', ['appliance_unit_id'], unique=False)
    op.create_index(op.f('ix_appliance_issue_line_current_work_order_id'), 'appliance_issue_line', ['current_work_order_id'], unique=False)
    op.create_index(op.f('ix_appliance_issue_line_installed_at'), 'appliance_issue_line', ['installed_at'], unique=False)
    op.create_index(op.f('ix_appliance_issue_line_issue_id'), 'appliance_issue_line', ['issue_id'], unique=False)
    op.create_index(op.f('ix_appliance_issue_line_status'), 'appliance_issue_line', ['status'], unique=False)
    op.create_index('ix_appliance_issue_line_unit_status', 'appliance_issue_line', ['appliance_unit_id', 'status'], unique=False)
    op.create_index('ix_appliance_issue_line_work_order_status', 'appliance_issue_line', ['current_work_order_id', 'status'], unique=False)
    op.create_table('appliance_movement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('appliance_unit_id', sa.Integer(), nullable=False),
    sa.Column('movement_type', sa.String(length=50), nullable=False),
    sa.Column('issue_id', sa.Integer(), nullable=True),
    sa.Column('issue_line_id', sa.Integer(), nullable=True),
    sa.Column('from_warehouse_id', sa.Integer(), nullable=True),
    sa.Column('to_warehouse_id', sa.Integer(), nullable=True),
    sa.Column('from_work_order_id', sa.Integer(), nullable=True),
    sa.Column('to_work_order_id', sa.Integer(), nullable=True),
    sa.Column('technician_id', sa.Integer(), nullable=True),
    sa.Column('related_appliance_unit_id', sa.Integer(), nullable=True),
    sa.Column('reason_code', sa.String(length=80), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('meta_json', sa.Text(), nullable=True),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['appliance_unit_id'], ['appliance_unit.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['from_warehouse_id'], ['warehouse.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['from_work_order_id'], ['work_orders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['issue_id'], ['appliance_issue.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['issue_line_id'], ['appliance_issue_line.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['related_appliance_unit_id'], ['appliance_unit.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['technician_id'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['to_warehouse_id'], ['warehouse.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['to_work_order_id'], ['work_orders.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appliance_movement_actor_id'), 'appliance_movement', ['actor_id'], unique=False)
    op.create_index(op.f('ix_appliance_movement_appliance_unit_id'), 'appliance_movement', ['appliance_unit_id'], unique=False)
    op.create_index(op.f('ix_appliance_movement_created_at'), 'appliance_movement', ['created_at'], unique=False)
    op.create_index(op.f('ix_appliance_movement_from_warehouse_id'), 'appliance_movement', ['from_warehouse_id'], unique=False)
    op.create_index(op.f('ix_appliance_movement_from_work_order_id'), 'appliance_movement', ['from_work_order_id'], unique=False)
    op.create_index('ix_appliance_movement_issue_created', 'appliance_movement', ['issue_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_appliance_movement_issue_id'), 'appliance_movement', ['issue_id'], unique=False)
    op.create_index(op.f('ix_appliance_movement_issue_line_id'), 'appliance_movement', ['issue_line_id'], unique=False)
    op.create_index(op.f('ix_appliance_movement_movement_type'), 'appliance_movement', ['movement_type'], unique=False)
    op.create_index(op.f('ix_appliance_movement_reason_code'), 'appliance_movement', ['reason_code'], unique=False)
    op.create_index(op.f('ix_appliance_movement_related_appliance_unit_id'), 'appliance_movement', ['related_appliance_unit_id'], unique=False)
    op.create_index(op.f('ix_appliance_movement_technician_id'), 'appliance_movement', ['technician_id'], unique=False)
    op.create_index(op.f('ix_appliance_movement_to_warehouse_id'), 'appliance_movement', ['to_warehouse_id'], unique=False)
    op.create_index(op.f('ix_appliance_movement_to_work_order_id'), 'appliance_movement', ['to_work_order_id'], unique=False)
    op.create_index('ix_appliance_movement_type_created', 'appliance_movement', ['movement_type', 'created_at'], unique=False)
    op.create_index('ix_appliance_movement_unit_created', 'appliance_movement', ['appliance_unit_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_appliance_movement_unit_created', table_name='appliance_movement')
    op.drop_index('ix_appliance_movement_type_created', table_name='appliance_movement')
    op.drop_index(op.f('ix_appliance_movement_to_work_order_id'), table_name='appliance_movement')
    op.drop_index(op.f('ix_appliance_movement_to_warehouse_id'), table_name='appliance_movement')
    op.drop_index(op.f('ix_appliance_movement_technician_id'), table_name='appliance_movement')
    op.drop_index(op.f('ix_appliance_movement_related_appliance_unit_id'), table_name='appliance_movement')
    op.drop_index(op.f('ix_appliance_movement_reason_code'), table_name='appliance_movement')
    op.drop_index(op.f('ix_appliance_movement_movement_type'), table_name='appliance_movement')
    op.drop_index(op.f('ix_appliance_movement_issue_line_id'), table_name='appliance_movement')
    op.drop_index(op.f('ix_appliance_movement_issue_id'), table_name='appliance_movement')
    op.drop_index('ix_appliance_movement_issue_created', table_name='appliance_movement')
    op.drop_index(op.f('ix_appliance_movement_from_work_order_id'), table_name='appliance_movement')
    op.drop_index(op.f('ix_appliance_movement_from_warehouse_id'), table_name='appliance_movement')
    op.drop_index(op.f('ix_appliance_movement_created_at'), table_name='appliance_movement')
    op.drop_index(op.f('ix_appliance_movement_appliance_unit_id'), table_name='appliance_movement')
    op.drop_index(op.f('ix_appliance_movement_actor_id'), table_name='appliance_movement')
    op.drop_table('appliance_movement')
    op.drop_index('ix_appliance_issue_line_work_order_status', table_name='appliance_issue_line')
    op.drop_index('ix_appliance_issue_line_unit_status', table_name='appliance_issue_line')
    op.drop_index(op.f('ix_appliance_issue_line_status'), table_name='appliance_issue_line')
    op.drop_index(op.f('ix_appliance_issue_line_issue_id'), table_name='appliance_issue_line')
    op.drop_index(op.f('ix_appliance_issue_line_installed_at'), table_name='appliance_issue_line')
    op.drop_index(op.f('ix_appliance_issue_line_current_work_order_id'), table_name='appliance_issue_line')
    op.drop_index(op.f('ix_appliance_issue_line_appliance_unit_id'), table_name='appliance_issue_line')
    op.drop_table('appliance_issue_line')
    op.drop_index(op.f('ix_appliance_issue_work_order_id'), table_name='appliance_issue')
    op.drop_index('ix_appliance_issue_work_order', table_name='appliance_issue')
    op.drop_index('ix_appliance_issue_warehouse_status', table_name='appliance_issue')
    op.drop_index(op.f('ix_appliance_issue_warehouse_id'), table_name='appliance_issue')
    op.drop_index(op.f('ix_appliance_issue_technician_id'), table_name='appliance_issue')
    op.drop_index('ix_appliance_issue_technician_date', table_name='appliance_issue')
    op.drop_index(op.f('ix_appliance_issue_status'), table_name='appliance_issue')
    op.drop_index(op.f('ix_appliance_issue_issued_by_id'), table_name='appliance_issue')
    op.drop_index(op.f('ix_appliance_issue_issued_at'), table_name='appliance_issue')
    op.drop_index(op.f('ix_appliance_issue_issue_number'), table_name='appliance_issue')
    op.drop_table('appliance_issue')
    # ### end Alembic commands ###
