"""add appliance inventory core

Revision ID: ab9ee67cc6c1
Revises: 28245b15c982
Create Date: 2026-08-18 12:47:16.112138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab9ee67cc6c1'
down_revision = '28245b15c982'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appliance_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_appliance_category_code'),
    sa.UniqueConstraint('name', name='uq_appliance_category_name')
    )
    op.create_index('ix_appliance_category_active_sort', 'appliance_category', ['is_active', 'sort_order'], unique=False)
    op.create_index(op.f('ix_appliance_category_code'), 'appliance_category', ['code'], unique=True)
    op.create_index(op.f('ix_appliance_category_created_by_id'), 'appliance_category', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_appliance_category_is_active'), 'appliance_category', ['is_active'], unique=False)
    op.create_index(op.f('ix_appliance_category_name'), 'appliance_category', ['name'], unique=True)
    op.create_index(op.f('ix_appliance_category_updated_by_id'), 'appliance_category', ['updated_by_id'], unique=False)
    op.create_table('appliance_receiving',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('receiving_number', sa.String(length=30), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('supplier_name', sa.String(length=200), nullable=True),
    sa.Column('invoice_number', sa.String(length=80), nullable=True),
    sa.Column('invoice_date', sa.Date(), nullable=True),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('attachment_path', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('posted_at', sa.DateTime(), nullable=True),
    sa.Column('posted_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['posted_by_id'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouse.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appliance_receiving_created_at'), 'appliance_receiving', ['created_at'], unique=False)
    op.create_index(op.f('ix_appliance_receiving_created_by_id'), 'appliance_receiving', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_appliance_receiving_invoice_date'), 'appliance_receiving', ['invoice_date'], unique=False)
    op.create_index(op.f('ix_appliance_receiving_invoice_number'), 'appliance_receiving', ['invoice_number'], unique=False)
    op.create_index(op.f('ix_appliance_receiving_posted_at'), 'appliance_receiving', ['posted_at'], unique=False)
    op.create_index(op.f('ix_appliance_receiving_posted_by_id'), 'appliance_receiving', ['posted_by_id'], unique=False)
    op.create_index('ix_appliance_receiving_received_at', 'appliance_receiving', ['received_at'], unique=False)
    op.create_index(op.f('ix_appliance_receiving_receiving_number'), 'appliance_receiving', ['receiving_number'], unique=True)
    op.create_index(op.f('ix_appliance_receiving_status'), 'appliance_receiving', ['status'], unique=False)
    op.create_index('ix_appliance_receiving_supplier_invoice', 'appliance_receiving', ['supplier_name', 'invoice_number'], unique=False)
    op.create_index(op.f('ix_appliance_receiving_supplier_name'), 'appliance_receiving', ['supplier_name'], unique=False)
    op.create_index(op.f('ix_appliance_receiving_updated_by_id'), 'appliance_receiving', ['updated_by_id'], unique=False)
    op.create_index(op.f('ix_appliance_receiving_warehouse_id'), 'appliance_receiving', ['warehouse_id'], unique=False)
    op.create_index('ix_appliance_receiving_warehouse_status', 'appliance_receiving', ['warehouse_id', 'status'], unique=False)
    op.create_table('appliance_receiving_line',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('receiving_id', sa.Integer(), nullable=False),
    sa.Column('line_no', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('brand', sa.String(length=100), nullable=True),
    sa.Column('model_number', sa.String(length=120), nullable=True),
    sa.Column('serial_number', sa.String(length=160), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('size_value', sa.Float(), nullable=True),
    sa.Column('size_unit', sa.String(length=20), nullable=True),
    sa.Column('condition', sa.String(length=40), nullable=False),
    sa.Column('unit_cost', sa.Float(), nullable=True),
    sa.Column('selling_price', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['appliance_category.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['receiving_id'], ['appliance_receiving.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('receiving_id', 'line_no', name='uq_appliance_receiving_line_number')
    )
    op.create_index(op.f('ix_appliance_receiving_line_brand'), 'appliance_receiving_line', ['brand'], unique=False)
    op.create_index('ix_appliance_receiving_line_category', 'appliance_receiving_line', ['category_id'], unique=False)
    op.create_index(op.f('ix_appliance_receiving_line_category_id'), 'appliance_receiving_line', ['category_id'], unique=False)
    op.create_index(op.f('ix_appliance_receiving_line_condition'), 'appliance_receiving_line', ['condition'], unique=False)
    op.create_index(op.f('ix_appliance_receiving_line_created_by_id'), 'appliance_receiving_line', ['created_by_id'], unique=False)
    op.create_index('ix_appliance_receiving_line_model', 'appliance_receiving_line', ['model_number'], unique=False)
    op.create_index(op.f('ix_appliance_receiving_line_model_number'), 'appliance_receiving_line', ['model_number'], unique=False)
    op.create_index(op.f('ix_appliance_receiving_line_receiving_id'), 'appliance_receiving_line', ['receiving_id'], unique=False)
    op.create_index('ix_appliance_receiving_line_serial', 'appliance_receiving_line', ['serial_number'], unique=False)
    op.create_index(op.f('ix_appliance_receiving_line_serial_number'), 'appliance_receiving_line', ['serial_number'], unique=False)
    op.create_index(op.f('ix_appliance_receiving_line_size_value'), 'appliance_receiving_line', ['size_value'], unique=False)
    op.create_index(op.f('ix_appliance_receiving_line_unit_cost'), 'appliance_receiving_line', ['unit_cost'], unique=False)
    op.create_index(op.f('ix_appliance_receiving_line_updated_by_id'), 'appliance_receiving_line', ['updated_by_id'], unique=False)
    op.create_table('appliance_unit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inventory_number', sa.String(length=40), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('receiving_line_id', sa.Integer(), nullable=False),
    sa.Column('brand', sa.String(length=100), nullable=True),
    sa.Column('model_number', sa.String(length=120), nullable=True),
    sa.Column('serial_number', sa.String(length=160), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('size_value', sa.Float(), nullable=True),
    sa.Column('size_unit', sa.String(length=20), nullable=True),
    sa.Column('condition', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('unit_cost', sa.Float(), nullable=True),
    sa.Column('selling_price', sa.Float(), nullable=True),
    sa.Column('current_work_order_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['appliance_category.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['current_work_order_id'], ['work_orders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['receiving_line_id'], ['appliance_receiving_line.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouse.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appliance_unit_brand'), 'appliance_unit', ['brand'], unique=False)
    op.create_index('ix_appliance_unit_brand_model', 'appliance_unit', ['brand', 'model_number'], unique=False)
    op.create_index(op.f('ix_appliance_unit_category_id'), 'appliance_unit', ['category_id'], unique=False)
    op.create_index('ix_appliance_unit_category_size_status', 'appliance_unit', ['category_id', 'size_value', 'status'], unique=False)
    op.create_index('ix_appliance_unit_category_status', 'appliance_unit', ['category_id', 'status'], unique=False)
    op.create_index(op.f('ix_appliance_unit_condition'), 'appliance_unit', ['condition'], unique=False)
    op.create_index(op.f('ix_appliance_unit_created_at'), 'appliance_unit', ['created_at'], unique=False)
    op.create_index(op.f('ix_appliance_unit_created_by_id'), 'appliance_unit', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_appliance_unit_current_work_order_id'), 'appliance_unit', ['current_work_order_id'], unique=False)
    op.create_index(op.f('ix_appliance_unit_inventory_number'), 'appliance_unit', ['inventory_number'], unique=True)
    op.create_index(op.f('ix_appliance_unit_model_number'), 'appliance_unit', ['model_number'], unique=False)
    op.create_index(op.f('ix_appliance_unit_receiving_line_id'), 'appliance_unit', ['receiving_line_id'], unique=True)
    op.create_index(op.f('ix_appliance_unit_serial_number'), 'appliance_unit', ['serial_number'], unique=False)
    op.create_index(op.f('ix_appliance_unit_size_value'), 'appliance_unit', ['size_value'], unique=False)
    op.create_index(op.f('ix_appliance_unit_status'), 'appliance_unit', ['status'], unique=False)
    op.create_index(op.f('ix_appliance_unit_updated_by_id'), 'appliance_unit', ['updated_by_id'], unique=False)
    op.create_index(op.f('ix_appliance_unit_warehouse_id'), 'appliance_unit', ['warehouse_id'], unique=False)
    op.create_index('ix_appliance_unit_warehouse_status', 'appliance_unit', ['warehouse_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_appliance_unit_warehouse_status', table_name='appliance_unit')
    op.drop_index(op.f('ix_appliance_unit_warehouse_id'), table_name='appliance_unit')
    op.drop_index(op.f('ix_appliance_unit_updated_by_id'), table_name='appliance_unit')
    op.drop_index(op.f('ix_appliance_unit_status'), table_name='appliance_unit')
    op.drop_index(op.f('ix_appliance_unit_size_value'), table_name='appliance_unit')
    op.drop_index(op.f('ix_appliance_unit_serial_number'), table_name='appliance_unit')
    op.drop_index(op.f('ix_appliance_unit_receiving_line_id'), table_name='appliance_unit')
    op.drop_index(op.f('ix_appliance_unit_model_number'), table_name='appliance_unit')
    op.drop_index(op.f('ix_appliance_unit_inventory_number'), table_name='appliance_unit')
    op.drop_index(op.f('ix_appliance_unit_current_work_order_id'), table_name='appliance_unit')
    op.drop_index(op.f('ix_appliance_unit_created_by_id'), table_name='appliance_unit')
    op.drop_index(op.f('ix_appliance_unit_created_at'), table_name='appliance_unit')
    op.drop_index(op.f('ix_appliance_unit_condition'), table_name='appliance_unit')
    op.drop_index('ix_appliance_unit_category_status', table_name='appliance_unit')
    op.drop_index('ix_appliance_unit_category_size_status', table_name='appliance_unit')
    op.drop_index(op.f('ix_appliance_unit_category_id'), table_name='appliance_unit')
    op.drop_index('ix_appliance_unit_brand_model', table_name='appliance_unit')
    op.drop_index(op.f('ix_appliance_unit_brand'), table_name='appliance_unit')
    op.drop_table('appliance_unit')
    op.drop_index(op.f('ix_appliance_receiving_line_updated_by_id'), table_name='appliance_receiving_line')
    op.drop_index(op.f('ix_appliance_receiving_line_unit_cost'), table_name='appliance_receiving_line')
    op.drop_index(op.f('ix_appliance_receiving_line_size_value'), table_name='appliance_receiving_line')
    op.drop_index(op.f('ix_appliance_receiving_line_serial_number'), table_name='appliance_receiving_line')
    op.drop_index('ix_appliance_receiving_line_serial', table_name='appliance_receiving_line')
    op.drop_index(op.f('ix_appliance_receiving_line_receiving_id'), table_name='appliance_receiving_line')
    op.drop_index(op.f('ix_appliance_receiving_line_model_number'), table_name='appliance_receiving_line')
    op.drop_index('ix_appliance_receiving_line_model', table_name='appliance_receiving_line')
    op.drop_index(op.f('ix_appliance_receiving_line_created_by_id'), table_name='appliance_receiving_line')
    op.drop_index(op.f('ix_appliance_receiving_line_condition'), table_name='appliance_receiving_line')
    op.drop_index(op.f('ix_appliance_receiving_line_category_id'), table_name='appliance_receiving_line')
    op.drop_index('ix_appliance_receiving_line_category', table_name='appliance_receiving_line')
    op.drop_index(op.f('ix_appliance_receiving_line_brand'), table_name='appliance_receiving_line')
    op.drop_table('appliance_receiving_line')
    op.drop_index('ix_appliance_receiving_warehouse_status', table_name='appliance_receiving')
    op.drop_index(op.f('ix_appliance_receiving_warehouse_id'), table_name='appliance_receiving')
    op.drop_index(op.f('ix_appliance_receiving_updated_by_id'), table_name='appliance_receiving')
    op.drop_index(op.f('ix_appliance_receiving_supplier_name'), table_name='appliance_receiving')
    op.drop_index('ix_appliance_receiving_supplier_invoice', table_name='appliance_receiving')
    op.drop_index(op.f('ix_appliance_receiving_status'), table_name='appliance_receiving')
    op.drop_index(op.f('ix_appliance_receiving_receiving_number'), table_name='appliance_receiving')
    op.drop_index('ix_appliance_receiving_received_at', table_name='appliance_receiving')
    op.drop_index(op.f('ix_appliance_receiving_posted_by_id'), table_name='appliance_receiving')
    op.drop_index(op.f('ix_appliance_receiving_posted_at'), table_name='appliance_receiving')
    op.drop_index(op.f('ix_appliance_receiving_invoice_number'), table_name='appliance_receiving')
    op.drop_index(op.f('ix_appliance_receiving_invoice_date'), table_name='appliance_receiving')
    op.drop_index(op.f('ix_appliance_receiving_created_by_id'), table_name='appliance_receiving')
    op.drop_index(op.f('ix_appliance_receiving_created_at'), table_name='appliance_receiving')
    op.drop_table('appliance_receiving')
    op.drop_index(op.f('ix_appliance_category_updated_by_id'), table_name='appliance_category')
    op.drop_index(op.f('ix_appliance_category_name'), table_name='appliance_category')
    op.drop_index(op.f('ix_appliance_category_is_active'), table_name='appliance_category')
    op.drop_index(op.f('ix_appliance_category_created_by_id'), table_name='appliance_category')
    op.drop_index(op.f('ix_appliance_category_code'), table_name='appliance_category')
    op.drop_index('ix_appliance_category_active_sort', table_name='appliance_category')
    op.drop_table('appliance_category')
    # ### end Alembic commands ###
